services:
  hadoop-master:
    image: docker.io/yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-master
    stdin_open: true
    tty: true
    volumes:
      - ./hadoop_project:/shared_volume:rw
    networks:
      - hadoop
    ports:
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
      - "19888:19888"
      - "8080:8080"
      - "9000:9000"
    hostname: hadoop-master
    restart: unless-stopped

  hadoop-slave1:
    image: docker.io/yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave1
    stdin_open: true
    tty: true
    depends_on:
      - hadoop-master
    networks:
      - hadoop
    ports:
      - 8040:8042
    hostname: hadoop-slave1
    restart: unless-stopped

  hadoop-slave2:
    image: docker.io/yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave2
    stdin_open: true
    tty: true
    depends_on:
      - hadoop-master
    networks:
      - hadoop
    ports:
      - 8041:8042
    hostname: hadoop-slave2
    restart: unless-stopped

networks:
  hadoop:
    driver: bridge
